version: '3.7'
services:
 define.php:
   volumes:
     - './app:/usr/src/app'

 define.nginx:
   volumes:
     - './app/public/:/usr/src/app'
     - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
   ports:
     - '${NGINX_PORT}:80'

 define.adminer:
   ports:
     - '${ADMINER_PORT}:8080'