version: '3.3'
services:
  define.mysql:
    container_name: define.mysql
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      backend:
        aliases:
          - define.mysql

  define.app:
    container_name: define.app
    image: mokocchi/dehia-define
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    depends_on: 
      - ${MYSQL_HOST}
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      SITE_BASE_URL: ${SITE_BASE_URL}
      AUTH_BASE_URL: ${AUTH_BASE_URL}
      COLLECT_BASE_URL: ${COLLECT_BASE_URL}
      RESULTS_BASE_URL: ${RESULTS_BASE_URL}
      WAIT_HOSTS: ${MYSQL_HOST}:3306
      WAIT_SLEEP_INTERVAL: 5
      WAIT_BEFORE: 10
      WAIT_TIMEOUT: 350
    restart: on-failure
    networks: 
      backend:
      dehia:
        aliases:
          - define.app

networks:
  dehia:
    external: true
  backend:
    external: false