version: '3.3'
services:
  define.mysql:
    container_name: define.mysql
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      backend:
        aliases:
          - define.mysql

  define.mysql.test:
    container_name: define.mysql.test
    image: mysql:8.0
    restart: on-failure
    depends_on: 
      - define.nginx
    expose: 
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_TEST_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_TEST_DATABASE}
      MYSQL_USER: ${MYSQL_TEST_USER}
      MYSQL_PASSWORD: ${MYSQL_TEST_PASSWORD}
    networks:
      backend:
        aliases:
          - define.mysql.test

  define.php:
    container_name: define.php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    depends_on: 
      - ${MYSQL_HOST}
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      SITE_BASE_URL: ${SITE_BASE_URL}
      AUTH_BASE_URL: ${AUTH_BASE_URL}
      COLLECT_BASE_URL: ${COLLECT_BASE_URL}
      RESULTS_BASE_URL: ${RESULTS_BASE_URL}

      MYSQL_TEST_DATABASE: ${MYSQL_TEST_DATABASE}
      MYSQL_TEST_PASSWORD: ${MYSQL_TEST_PASSWORD}
      MYSQL_TEST_USER: ${MYSQL_TEST_USER}
      MYSQL_TEST_HOST: ${MYSQL_TEST_HOST}
      SITE_BASE_URL_TEST: ${SITE_BASE_URL_TEST}
      AUTH_BASE_URL_TEST: ${AUTH_BASE_URL_TEST}
      WAIT_HOSTS: ${MYSQL_HOST}:3306
      WAIT_SLEEP_INTERVAL: 5
      WAIT_BEFORE: 10
      WAIT_TIMEOUT: 350
    restart: on-failure
    user: ${LOCAL_USER}
    networks: 
      dehia:
      backend:
        aliases:
          - define.php

  define.nginx:
    container_name: define.nginx
    image: nginx:1.17-alpine
    restart: on-failure
    depends_on:
      - define.php
    networks:
      backend:
      dehia:
        aliases:
          - define.nginx

  define.adminer:
    container_name: define.adminer
    image: adminer:4.8.0
    depends_on: 
      - define.mysql
    restart: on-failure
    networks: 
      - backend

networks:
  dehia:
    external: true
  backend:
    external: false