version: '3.3'
services:
 define.php:
   volumes:
     - './app/src:/usr/src/app/src'

 define.nginx:
   volumes:
     - './app/public/:/usr/src/app'
     - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'

 define.adminer:
   ports:
     - '${ADMINER_PORT}:8080'