version: '3.3'
services:
  define.mysql:
    container_name: define.mysql
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      backend:
        aliases:
          - define.mysql

  define.php:
    container_name: define.php
    image: mokocchi/dehia-define
    # build:
    #   context: .
    #   dockerfile: docker/php/Dockerfile
    depends_on: 
      - ${MYSQL_HOST}
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      SITE_BASE_URL: ${SITE_BASE_URL}
      AUTH_BASE_URL: ${AUTH_BASE_URL}
      COLLECT_BASE_URL: ${COLLECT_BASE_URL}
      RESULTS_BASE_URL: ${RESULTS_BASE_URL}
      WAIT_HOSTS: ${MYSQL_HOST}:3306
      WAIT_SLEEP_INTERVAL: 5
      WAIT_BEFORE: 10
      WAIT_TIMEOUT: 350
    restart: on-failure
    user: ${LOCAL_USER}
    networks: 
      dehia:
      backend:
        aliases:
          - define.php

  define.nginx:
    container_name: define.nginx
    image: nginx:1.17-alpine
    restart: on-failure
    depends_on:
      - define.php
    volumes:
     - './app/public/:/usr/src/app'
     - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    networks:
      backend:
      dehia:
        aliases:
          - define.nginx

networks:
  dehia:
    external: true
  backend:
    external: false