version: '3.7'
services:
  define.mysql:
    container_name: define.mysql
    image: mysql:8.0
    restart: on-failure
    expose: 
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      backend:
        aliases:
          - define.mysql

  define.php:
    container_name: define.php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    user: ${LOCAL_USER}
    expose: 
      - 9000
    networks: 
      dehia:
      backend:
        aliases:
          - define.php

  define.nginx:
    container_name: define.nginx
    image: nginx:1.15.3-alpine
    restart: on-failure
    depends_on:
      - define.php
    networks:
      backend:
      dehia:
        aliases:
          - define.nginx

  define.adminer:
    container_name: define.adminer
    image: adminer
    restart: on-failure
    networks: 
      - backend

networks:
  dehia:
    external: true
  backend:
    external: false